# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-03-08 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeiboUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('uid', models.CharField(db_index=True, max_length=10, null=True, unique=True, verbose_name='微博uid')),
                ('access_token', models.CharField(db_index=True, max_length=32, verbose_name='微博授权密钥')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '微博用户表',
                'verbose_name_plural': '微博用户表',
                'db_table': 'weibouser',
            },
        ),
    ]
